# Generated by Django 4.2.23 on 2025-08-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KBArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pattern', models.CharField(help_text='Regex to match title or labels', max_length=500)),
                ('solution', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'kb_article',
                'ordering': ['-priority', 'id'],
            },
        ),
    ]
