# Generated by Django 4.2.23 on 2025-08-30 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('firing', 'Firing'), ('resolved', 'Resolved'), ('acked', 'Acknowledged')], default='firing', max_length=16)),
                ('count', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'alert_group',
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('firing', 'Firing'), ('resolved', 'Resolved'), ('acked', 'Acknowledged')], default='firing', max_length=16)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('warning', 'Warning'), ('info', 'Info'), ('ok', 'OK')], default='warning', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('annotations', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('resource', models.CharField(blank=True, default='', max_length=128)),
                ('service', models.CharField(blank=True, default='', max_length=128)),
                ('metric', models.CharField(blank=True, default='', max_length=128)),
                ('namespace', models.CharField(blank=True, default='', max_length=128)),
                ('generator_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alertgroup')),
            ],
            options={
                'db_table': 'alert_event',
                'indexes': [models.Index(fields=['fingerprint', 'status'], name='alert_event_fingerp_061552_idx'), models.Index(fields=['source', 'created_at'], name='alert_event_source_76b714_idx')],
            },
        ),
    ]
